src_dir: ../src
out_dir: ../build_src
patch_dir: patch
haiku_headers_dir: /boot/system/develop/headers/os
header_files:
  - [ support/Archivable.h, Archivable ] # ignore Archiver, Unarchiver
  - app/Application.h
#  - app/Clipboard.h
#  - app/Cursor.h
  - app/Handler.h
#  - app/Invoker.h
  - app/Looper.h
  - app/Message.h
#  - app/MessageFilter.h
  - app/MessageQueue.h
#  - app/MessageRunner.h
  - app/Messenger.h
#  - app/Notification.h
#  - app/Roster.h
#  - interface/Window.h
#  - interface/View.h
#  - interface/ScrollView.h
#  - interface/Layout.h
#  - interface/LayoutItem.h
  - interface/Rect.h
  - interface/Point.h
  - interface/Size.h
